// -------------------------------------------------------------
// 
// File Name: C:\Users\eslam\OneDrive\Desktop\Si clash\Fractional Sample Rate Conversion\Matlab files\codegen\Final20Notch24\hdlsrc\Final20Notch24.v
// Created: 2025-11-22 08:25:17
// 
// Generated by MATLAB 25.2, MATLAB Coder 25.2 and HDL Coder 25.2
// 
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Design base rate: 1
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        1
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// dataOut                       ce_out        1
// validOut                      ce_out        1
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Final20Notch24
// Source Path: Final20Notch24
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Final20Notch24
          (clk,
           reset,
           clk_enable,
           dataIn,
           validIn,
           ce_out,
           dataOut,
           validOut);


  input   clk;
  input   reset;
  input   clk_enable;
  input   signed [15:0] dataIn;  // sfix16_En15
  input   validIn;
  output  ce_out;
  output  signed [15:0] dataOut;  // sfix16_En15
  output  validOut;


  wire signed [15:0] varargout_1;  // sfix16_En15
  wire varargout_2;


  // Generated by HDL IP Designer.
  dsphdl_BiquadFilter u_dsphdl_BiquadFilter (.clk(clk),
                                             .reset(reset),
                                             .enb(clk_enable),
                                             .dataIn(dataIn),  // sfix16_En15
                                             .validIn(validIn),
                                             .dataOut(varargout_1),  // sfix16_En15
                                             .validOut(varargout_2)
                                             );

  assign dataOut = varargout_1;

  assign validOut = varargout_2;

  assign ce_out = clk_enable;

endmodule  // Final20Notch24

