// -------------------------------------------------------------
// 
// File Name: C:\Users\eslam\OneDrive\Desktop\Si clash\Fractional Sample Rate Conversion\Matlab files\codegen\FinalFractionalDecimator\hdlsrc\FinalFractionalDecimator.v
// Created: 2025-11-22 18:07:29
// 
// Generated by MATLAB 25.2, MATLAB Coder 25.2 and HDL Coder 25.2
// 
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Design base rate: 1
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        1
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// dataOut                       ce_out        1
// validOut                      ce_out        1
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: FinalFractionalDecimator
// Source Path: FinalFractionalDecimator
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module FinalFractionalDecimator
          (clk,
           reset,
           clk_enable,
           dataIn,
           validIn,
           ce_out,
           dataOut,
           validOut);


  input   clk;
  input   reset;
  input   clk_enable;
  input   signed [15:0] dataIn;  // sfix16_En15
  input   validIn;
  output  ce_out;
  output  signed [15:0] dataOut;  // sfix16_En15
  output  validOut;


  wire signed [15:0] varargout_1;  // sfix16_En15
  wire varargout_2;


  // Generated by HDL IP Designer.
  dsphdl_FIRRateConverter u_dsphdl_FIRRateConverter (.clk(clk),
                                                     .reset(reset),
                                                     .enb(clk_enable),
                                                     .dataIn(dataIn),  // sfix16_En15
                                                     .validIn(validIn),
                                                     .dataOut(varargout_1),  // sfix16_En15
                                                     .validOut(varargout_2)
                                                     );

  assign dataOut = varargout_1;

  assign validOut = varargout_2;

  assign ce_out = clk_enable;

endmodule  // FinalFractionalDecimator

