// Hierarchy Level: 0

module fractional_decimator_block 
          (clk,
           reset,
           clk_enable,
           dataIn,
           validIn,
           ce_out,
           dataOut,
           validOut);


  input   clk;
  input   reset;
  input   clk_enable;
  input   signed [15:0] dataIn;  // sfix16_En15
  input   validIn;
  output  ce_out;
  output  signed [15:0] dataOut;  // sfix16_En15
  output  validOut;


  wire signed [15:0] varargout_1;  // sfix16_En15
  wire varargout_2;


  // Generated by HDL IP Designer.
  dsphdl_FIRRateConverter u_dsphdl_FIRRateConverter (.clk(clk),
                                                     .reset(reset),
                                                     .enb(clk_enable),
                                                     .dataIn(dataIn),  // sfix16_En15
                                                     .validIn(validIn),
                                                     .dataOut(varargout_1),  // sfix16_En15
                                                     .validOut(varargout_2)
                                                     );

  assign dataOut = varargout_1;

  assign validOut = varargout_2;

  assign ce_out = clk_enable;

endmodule  
