// -------------------------------------------------------------
// 
// File Name: C:\Users\eslam\OneDrive\Desktop\Si clash\Fractional Sample Rate Conversion\Matlab files\codegen\Final20Notch5\hdlsrc\BiquadDF2Section1.v
// Created: 2025-11-22 10:34:45
// 
// Generated by MATLAB 25.2, MATLAB Coder 25.2 and HDL Coder 25.2
// 
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: BiquadDF2Section1
// Source Path: Final20Notch5/dsphdl.BiquadFilter/BiquadDF2Section1
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module BiquadDF2Section1
          (clk,
           reset,
           enb,
           dataIn,
           validIn,
           dataOut,
           validOut);


  input   clk;
  input   reset;
  input   enb;
  input   signed [15:0] dataIn;  // sfix16_En15
  input   validIn;
  output  signed [15:0] dataOut;  // sfix16_En15
  output  validOut;


  reg signed [15:0] inReg;  // sfix16_En15
  reg signed [15:0] numPrePipe1;  // sfix16_En15
  wire signed [35:0] numProd1;  // sfix36_En33
  reg signed [35:0] numPostPipe1;  // sfix36_En33
  reg  inValidReg;
  reg  [1:0] intdelay_reg;  // ufix1 [2]
  wire inValidRegDly;
  reg signed [15:0] numPrePipe2;  // sfix16_En15
  wire signed [35:0] numProd2;  // sfix36_En33
  reg signed [35:0] numPostPipe2;  // sfix36_En33
  reg signed [15:0] numPrePipe3;  // sfix16_En15
  wire signed [35:0] numProd3;  // sfix36_En33
  reg signed [35:0] numPostPipe3;  // sfix36_En33
  wire signed [15:0] denOut;  // sfix16_En15
  wire signed [35:0] denProd1;  // sfix36_En33
  wire signed [35:0] denProd2;  // sfix36_En33
  wire signed [37:0] adder_add_cast;  // sfix38_En33
  wire signed [37:0] adder_add_cast_1;  // sfix38_En33
  wire signed [37:0] denSum3;  // sfix38_En33
  reg signed [37:0] state2;  // sfix38_En33
  wire signed [37:0] adder_add_cast_2;  // sfix38_En33
  wire signed [37:0] denSum2b;  // sfix38_En33
  wire signed [37:0] adder_add_cast_3;  // sfix38_En33
  wire signed [37:0] denSum2a;  // sfix38_En33
  reg signed [37:0] state1;  // sfix38_En33
  wire signed [37:0] adder_add_cast_4;  // sfix38_En33
  wire signed [37:0] denSum1;  // sfix38_En33
  reg signed [15:0] dataOut_1;  // sfix16_En15
  reg  [3:0] intdelay_reg_1;  // ufix1 [4]


  always @(posedge clk)
    begin : InRegister_process
      if (reset == 1'b0) begin
        inReg <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          inReg <= dataIn;
        end
      end
    end

  always @(posedge clk)
    begin : numPreReg1_process
      if (reset == 1'b0) begin
        numPrePipe1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          numPrePipe1 <= inReg;
        end
      end
    end

  assign numProd1 = {{2{numPrePipe1[15]}}, {numPrePipe1, 18'b000000000000000000}};

  always @(posedge clk)
    begin : numPostReg1_process
      if (reset == 1'b0) begin
        numPostPipe1 <= 36'sh000000000;
      end
      else begin
        if (enb) begin
          numPostPipe1 <= numProd1;
        end
      end
    end

  always @(posedge clk)
    begin : InValidRegister_process
      if (reset == 1'b0) begin
        inValidReg <= 1'b0;
      end
      else begin
        if (enb) begin
          inValidReg <= validIn;
        end
      end
    end

  always @(posedge clk)
    begin : intdelay_process
      if (reset == 1'b0) begin
        intdelay_reg <= {2{1'b0}};
      end
      else begin
        if (enb) begin
          intdelay_reg[0] <= inValidReg;
          intdelay_reg[1] <= intdelay_reg[0];
        end
      end
    end

  assign inValidRegDly = intdelay_reg[1];

  always @(posedge clk)
    begin : numPreReg2_process
      if (reset == 1'b0) begin
        numPrePipe2 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          numPrePipe2 <= inReg;
        end
      end
    end

  assign numProd2 = 20'sb11000000000000000000 * numPrePipe2;

  always @(posedge clk)
    begin : numPostReg2_process
      if (reset == 1'b0) begin
        numPostPipe2 <= 36'sh000000000;
      end
      else begin
        if (enb) begin
          numPostPipe2 <= numProd2;
        end
      end
    end

  always @(posedge clk)
    begin : numPreReg3_process
      if (reset == 1'b0) begin
        numPrePipe3 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          numPrePipe3 <= inReg;
        end
      end
    end

  assign numProd3 = {{2{numPrePipe3[15]}}, {numPrePipe3, 18'b000000000000000000}};

  always @(posedge clk)
    begin : numPostReg3_process
      if (reset == 1'b0) begin
        numPostPipe3 <= 36'sh000000000;
      end
      else begin
        if (enb) begin
          numPostPipe3 <= numProd3;
        end
      end
    end

  assign denProd1 = 20'sb00111100101110011110 * denOut;

  assign denProd2 = 20'sb11000110010111111100 * denOut;

  assign adder_add_cast = {{2{numPostPipe3[35]}}, numPostPipe3};
  assign adder_add_cast_1 = {{2{denProd2[35]}}, denProd2};
  assign denSum3 = adder_add_cast + adder_add_cast_1;

  always @(posedge clk)
    begin : State2Reg_process
      if (reset == 1'b0) begin
        state2 <= 38'sh0000000000;
      end
      else begin
        if (enb && inValidRegDly) begin
          state2 <= denSum3;
        end
      end
    end

  assign adder_add_cast_2 = {{2{numPostPipe2[35]}}, numPostPipe2};
  assign denSum2b = adder_add_cast_2 + state2;

  assign adder_add_cast_3 = {{2{denProd1[35]}}, denProd1};
  assign denSum2a = denSum2b + adder_add_cast_3;

  always @(posedge clk)
    begin : State1Reg_process
      if (reset == 1'b0) begin
        state1 <= 38'sh0000000000;
      end
      else begin
        if (enb && inValidRegDly) begin
          state1 <= denSum2a;
        end
      end
    end

  assign adder_add_cast_4 = {{2{numPostPipe1[35]}}, numPostPipe1};
  assign denSum1 = adder_add_cast_4 + state1;

  assign denOut = (((denSum1[37] == 1'b0) && (denSum1[36:33] != 4'b0000)) || ((denSum1[37] == 1'b0) && (denSum1[33:18] == 16'sb0111111111111111)) ? 16'sb0111111111111111 :
              ((denSum1[37] == 1'b1) && (denSum1[36:33] != 4'b1111) ? 16'sb1000000000000000 :
              denSum1[33:18] + $signed({1'b0, denSum1[17] & (( ~ denSum1[37]) | (|denSum1[16:0]))})));

  always @(posedge clk)
    begin : outputReg_process
      if (reset == 1'b0) begin
        dataOut_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          dataOut_1 <= denOut;
        end
      end
    end

  always @(posedge clk)
    begin : intdelay_1_process
      if (reset == 1'b0) begin
        intdelay_reg_1 <= {4{1'b0}};
      end
      else begin
        if (enb) begin
          intdelay_reg_1[0] <= validIn;
          intdelay_reg_1[32'sd3:32'sd1] <= intdelay_reg_1[32'sd2:32'sd0];
        end
      end
    end

  assign validOut = intdelay_reg_1[3];

  assign dataOut = dataOut_1;

endmodule  // BiquadDF2Section1

