// -------------------------------------------------------------
// 
// File Name: C:\Users\eslam\OneDrive\Desktop\Si clash\Fractional Sample Rate Conversion\Matlab files\codegen\finalCIC\hdlsrc\cSection.v
// Created: 2025-11-21 17:16:16
// 
// Generated by MATLAB 25.2, MATLAB Coder 25.2 and HDL Coder 25.2
// 
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: cSection
// Source Path: finalCIC/CICDecimation/cSection
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module cSection
          (clk,
           reset,
           enb,
           dsOut_re,
           dsOut_im,
           ds_vout,
           internalReset,
           combOut_re,
           combOut_im,
           c_vout);


  input   clk;
  input   reset;
  input   enb;
  input   signed [19:0] dsOut_re;  // sfix20_En15
  input   signed [19:0] dsOut_im;  // sfix20_En15
  input   ds_vout;
  input   internalReset;
  output  signed [19:0] combOut_re;  // sfix20_En15
  output  signed [19:0] combOut_im;  // sfix20_En15
  output  c_vout;


  reg  cBuff_vout1;
  reg  cBuff_vout2;
  reg  cBuff_vout3;
  reg  cBuff_vout4;
  wire signed [19:0] invalidOut_re_1;  // sfix20_En15
  reg signed [19:0] cDelay_re1;  // sfix20_En15
  wire signed [20:0] subtractor_sub_cast;  // sfix21_En15
  wire signed [20:0] subtractor_sub_cast_1;  // sfix21_En15
  wire signed [20:0] subOut_re1;  // sfix21_En15
  wire signed [19:0] cOut_re1;  // sfix20_En15
  reg signed [19:0] cBuff_re1;  // sfix20_En15
  reg signed [19:0] cDelay_re2;  // sfix20_En15
  wire signed [20:0] subtractor_sub_cast_2;  // sfix21_En15
  wire signed [20:0] subtractor_sub_cast_3;  // sfix21_En15
  wire signed [20:0] subOut_re2;  // sfix21_En15
  wire signed [19:0] cOut_re2;  // sfix20_En15
  reg signed [19:0] cBuff_re2;  // sfix20_En15
  reg signed [19:0] cDelay_re3;  // sfix20_En15
  wire signed [20:0] subtractor_sub_cast_4;  // sfix21_En15
  wire signed [20:0] subtractor_sub_cast_5;  // sfix21_En15
  wire signed [20:0] subOut_re3;  // sfix21_En15
  wire signed [19:0] cOut_re3;  // sfix20_En15
  reg signed [19:0] cBuff_re3;  // sfix20_En15
  reg signed [19:0] cDelay_re4;  // sfix20_En15
  wire signed [20:0] subtractor_sub_cast_6;  // sfix21_En15
  wire signed [20:0] subtractor_sub_cast_7;  // sfix21_En15
  wire signed [20:0] subOut_re4;  // sfix21_En15
  wire signed [19:0] cOut_re4;  // sfix20_En15
  reg signed [19:0] cBuff_re4;  // sfix20_En15
  wire signed [19:0] combOutreg_re;  // sfix20_En15
  reg signed [19:0] combOut_re_1;  // sfix20_En15
  wire signed [19:0] invalidOut_im_1;  // sfix20_En15
  reg signed [19:0] cDelay_im1;  // sfix20_En15
  wire signed [20:0] subtractor_sub_cast_8;  // sfix21_En15
  wire signed [20:0] subtractor_sub_cast_9;  // sfix21_En15
  wire signed [20:0] subOut_im1;  // sfix21_En15
  wire signed [19:0] cOut_im1;  // sfix20_En15
  reg signed [19:0] cBuff_im1;  // sfix20_En15
  reg signed [19:0] cDelay_im2;  // sfix20_En15
  wire signed [20:0] subtractor_sub_cast_10;  // sfix21_En15
  wire signed [20:0] subtractor_sub_cast_11;  // sfix21_En15
  wire signed [20:0] subOut_im2;  // sfix21_En15
  wire signed [19:0] cOut_im2;  // sfix20_En15
  reg signed [19:0] cBuff_im2;  // sfix20_En15
  reg signed [19:0] cDelay_im3;  // sfix20_En15
  wire signed [20:0] subtractor_sub_cast_12;  // sfix21_En15
  wire signed [20:0] subtractor_sub_cast_13;  // sfix21_En15
  wire signed [20:0] subOut_im3;  // sfix21_En15
  wire signed [19:0] cOut_im3;  // sfix20_En15
  reg signed [19:0] cBuff_im3;  // sfix20_En15
  reg signed [19:0] cDelay_im4;  // sfix20_En15
  wire signed [20:0] subtractor_sub_cast_14;  // sfix21_En15
  wire signed [20:0] subtractor_sub_cast_15;  // sfix21_En15
  wire signed [20:0] subOut_im4;  // sfix21_En15
  wire signed [19:0] cOut_im4;  // sfix20_En15
  reg signed [19:0] cBuff_im4;  // sfix20_En15
  wire signed [19:0] combOutreg_im;  // sfix20_En15
  reg signed [19:0] combOut_im_1;  // sfix20_En15
  reg  c_vout_1;


  always @(posedge clk)
    begin : intdelay_process
      if (reset == 1'b0) begin
        cBuff_vout1 <= 1'b0;
      end
      else begin
        if (enb) begin
          if (internalReset == 1'b1) begin
            cBuff_vout1 <= 1'b0;
          end
          else begin
            cBuff_vout1 <= ds_vout;
          end
        end
      end
    end

  always @(posedge clk)
    begin : intdelay_1_process
      if (reset == 1'b0) begin
        cBuff_vout2 <= 1'b0;
      end
      else begin
        if (enb) begin
          if (internalReset == 1'b1) begin
            cBuff_vout2 <= 1'b0;
          end
          else begin
            cBuff_vout2 <= cBuff_vout1;
          end
        end
      end
    end

  always @(posedge clk)
    begin : intdelay_2_process
      if (reset == 1'b0) begin
        cBuff_vout3 <= 1'b0;
      end
      else begin
        if (enb) begin
          if (internalReset == 1'b1) begin
            cBuff_vout3 <= 1'b0;
          end
          else begin
            cBuff_vout3 <= cBuff_vout2;
          end
        end
      end
    end

  always @(posedge clk)
    begin : intdelay_3_process
      if (reset == 1'b0) begin
        cBuff_vout4 <= 1'b0;
      end
      else begin
        if (enb) begin
          if (internalReset == 1'b1) begin
            cBuff_vout4 <= 1'b0;
          end
          else begin
            cBuff_vout4 <= cBuff_vout3;
          end
        end
      end
    end

  assign invalidOut_re_1 = 20'sb00000000000000000000;

  always @(posedge clk)
    begin : intdelay_4_process
      if (reset == 1'b0) begin
        cDelay_re1 <= 20'sb00000000000000000000;
      end
      else begin
        if (enb) begin
          if (internalReset == 1'b1) begin
            cDelay_re1 <= 20'sb00000000000000000000;
          end
          else begin
            if (ds_vout) begin
              cDelay_re1 <= dsOut_re;
            end
          end
        end
      end
    end

  assign subtractor_sub_cast = {dsOut_re[19], dsOut_re};
  assign subtractor_sub_cast_1 = {cDelay_re1[19], cDelay_re1};
  assign subOut_re1 = subtractor_sub_cast - subtractor_sub_cast_1;

  assign cOut_re1 = subOut_re1[19:0];

  always @(posedge clk)
    begin : intdelay_5_process
      if (reset == 1'b0) begin
        cBuff_re1 <= 20'sb00000000000000000000;
      end
      else begin
        if (enb) begin
          if (internalReset == 1'b1) begin
            cBuff_re1 <= 20'sb00000000000000000000;
          end
          else begin
            cBuff_re1 <= cOut_re1;
          end
        end
      end
    end

  always @(posedge clk)
    begin : intdelay_6_process
      if (reset == 1'b0) begin
        cDelay_re2 <= 20'sb00000000000000000000;
      end
      else begin
        if (enb) begin
          if (internalReset == 1'b1) begin
            cDelay_re2 <= 20'sb00000000000000000000;
          end
          else begin
            if (cBuff_vout1) begin
              cDelay_re2 <= cBuff_re1;
            end
          end
        end
      end
    end

  assign subtractor_sub_cast_2 = {cBuff_re1[19], cBuff_re1};
  assign subtractor_sub_cast_3 = {cDelay_re2[19], cDelay_re2};
  assign subOut_re2 = subtractor_sub_cast_2 - subtractor_sub_cast_3;

  assign cOut_re2 = subOut_re2[19:0];

  always @(posedge clk)
    begin : intdelay_7_process
      if (reset == 1'b0) begin
        cBuff_re2 <= 20'sb00000000000000000000;
      end
      else begin
        if (enb) begin
          if (internalReset == 1'b1) begin
            cBuff_re2 <= 20'sb00000000000000000000;
          end
          else begin
            cBuff_re2 <= cOut_re2;
          end
        end
      end
    end

  always @(posedge clk)
    begin : intdelay_8_process
      if (reset == 1'b0) begin
        cDelay_re3 <= 20'sb00000000000000000000;
      end
      else begin
        if (enb) begin
          if (internalReset == 1'b1) begin
            cDelay_re3 <= 20'sb00000000000000000000;
          end
          else begin
            if (cBuff_vout2) begin
              cDelay_re3 <= cBuff_re2;
            end
          end
        end
      end
    end

  assign subtractor_sub_cast_4 = {cBuff_re2[19], cBuff_re2};
  assign subtractor_sub_cast_5 = {cDelay_re3[19], cDelay_re3};
  assign subOut_re3 = subtractor_sub_cast_4 - subtractor_sub_cast_5;

  assign cOut_re3 = subOut_re3[19:0];

  always @(posedge clk)
    begin : intdelay_9_process
      if (reset == 1'b0) begin
        cBuff_re3 <= 20'sb00000000000000000000;
      end
      else begin
        if (enb) begin
          if (internalReset == 1'b1) begin
            cBuff_re3 <= 20'sb00000000000000000000;
          end
          else begin
            cBuff_re3 <= cOut_re3;
          end
        end
      end
    end

  always @(posedge clk)
    begin : intdelay_10_process
      if (reset == 1'b0) begin
        cDelay_re4 <= 20'sb00000000000000000000;
      end
      else begin
        if (enb) begin
          if (internalReset == 1'b1) begin
            cDelay_re4 <= 20'sb00000000000000000000;
          end
          else begin
            if (cBuff_vout3) begin
              cDelay_re4 <= cBuff_re3;
            end
          end
        end
      end
    end

  assign subtractor_sub_cast_6 = {cBuff_re3[19], cBuff_re3};
  assign subtractor_sub_cast_7 = {cDelay_re4[19], cDelay_re4};
  assign subOut_re4 = subtractor_sub_cast_6 - subtractor_sub_cast_7;

  assign cOut_re4 = subOut_re4[19:0];

  always @(posedge clk)
    begin : intdelay_11_process
      if (reset == 1'b0) begin
        cBuff_re4 <= 20'sb00000000000000000000;
      end
      else begin
        if (enb) begin
          if (internalReset == 1'b1) begin
            cBuff_re4 <= 20'sb00000000000000000000;
          end
          else begin
            cBuff_re4 <= cOut_re4;
          end
        end
      end
    end

  assign combOutreg_re = (cBuff_vout4 == 1'b0 ? invalidOut_re_1 :
              cBuff_re4);

  always @(posedge clk)
    begin : intdelay_12_process
      if (reset == 1'b0) begin
        combOut_re_1 <= 20'sb00000000000000000000;
      end
      else begin
        if (enb) begin
          if (internalReset == 1'b1) begin
            combOut_re_1 <= 20'sb00000000000000000000;
          end
          else begin
            combOut_re_1 <= combOutreg_re;
          end
        end
      end
    end

  assign invalidOut_im_1 = 20'sb00000000000000000000;

  always @(posedge clk)
    begin : intdelay_13_process
      if (reset == 1'b0) begin
        cDelay_im1 <= 20'sb00000000000000000000;
      end
      else begin
        if (enb) begin
          if (internalReset == 1'b1) begin
            cDelay_im1 <= 20'sb00000000000000000000;
          end
          else begin
            if (ds_vout) begin
              cDelay_im1 <= dsOut_im;
            end
          end
        end
      end
    end

  assign subtractor_sub_cast_8 = {dsOut_im[19], dsOut_im};
  assign subtractor_sub_cast_9 = {cDelay_im1[19], cDelay_im1};
  assign subOut_im1 = subtractor_sub_cast_8 - subtractor_sub_cast_9;

  assign cOut_im1 = subOut_im1[19:0];

  always @(posedge clk)
    begin : intdelay_14_process
      if (reset == 1'b0) begin
        cBuff_im1 <= 20'sb00000000000000000000;
      end
      else begin
        if (enb) begin
          if (internalReset == 1'b1) begin
            cBuff_im1 <= 20'sb00000000000000000000;
          end
          else begin
            cBuff_im1 <= cOut_im1;
          end
        end
      end
    end

  always @(posedge clk)
    begin : intdelay_15_process
      if (reset == 1'b0) begin
        cDelay_im2 <= 20'sb00000000000000000000;
      end
      else begin
        if (enb) begin
          if (internalReset == 1'b1) begin
            cDelay_im2 <= 20'sb00000000000000000000;
          end
          else begin
            if (cBuff_vout1) begin
              cDelay_im2 <= cBuff_im1;
            end
          end
        end
      end
    end

  assign subtractor_sub_cast_10 = {cBuff_im1[19], cBuff_im1};
  assign subtractor_sub_cast_11 = {cDelay_im2[19], cDelay_im2};
  assign subOut_im2 = subtractor_sub_cast_10 - subtractor_sub_cast_11;

  assign cOut_im2 = subOut_im2[19:0];

  always @(posedge clk)
    begin : intdelay_16_process
      if (reset == 1'b0) begin
        cBuff_im2 <= 20'sb00000000000000000000;
      end
      else begin
        if (enb) begin
          if (internalReset == 1'b1) begin
            cBuff_im2 <= 20'sb00000000000000000000;
          end
          else begin
            cBuff_im2 <= cOut_im2;
          end
        end
      end
    end

  always @(posedge clk)
    begin : intdelay_17_process
      if (reset == 1'b0) begin
        cDelay_im3 <= 20'sb00000000000000000000;
      end
      else begin
        if (enb) begin
          if (internalReset == 1'b1) begin
            cDelay_im3 <= 20'sb00000000000000000000;
          end
          else begin
            if (cBuff_vout2) begin
              cDelay_im3 <= cBuff_im2;
            end
          end
        end
      end
    end

  assign subtractor_sub_cast_12 = {cBuff_im2[19], cBuff_im2};
  assign subtractor_sub_cast_13 = {cDelay_im3[19], cDelay_im3};
  assign subOut_im3 = subtractor_sub_cast_12 - subtractor_sub_cast_13;

  assign cOut_im3 = subOut_im3[19:0];

  always @(posedge clk)
    begin : intdelay_18_process
      if (reset == 1'b0) begin
        cBuff_im3 <= 20'sb00000000000000000000;
      end
      else begin
        if (enb) begin
          if (internalReset == 1'b1) begin
            cBuff_im3 <= 20'sb00000000000000000000;
          end
          else begin
            cBuff_im3 <= cOut_im3;
          end
        end
      end
    end

  always @(posedge clk)
    begin : intdelay_19_process
      if (reset == 1'b0) begin
        cDelay_im4 <= 20'sb00000000000000000000;
      end
      else begin
        if (enb) begin
          if (internalReset == 1'b1) begin
            cDelay_im4 <= 20'sb00000000000000000000;
          end
          else begin
            if (cBuff_vout3) begin
              cDelay_im4 <= cBuff_im3;
            end
          end
        end
      end
    end

  assign subtractor_sub_cast_14 = {cBuff_im3[19], cBuff_im3};
  assign subtractor_sub_cast_15 = {cDelay_im4[19], cDelay_im4};
  assign subOut_im4 = subtractor_sub_cast_14 - subtractor_sub_cast_15;

  assign cOut_im4 = subOut_im4[19:0];

  always @(posedge clk)
    begin : intdelay_20_process
      if (reset == 1'b0) begin
        cBuff_im4 <= 20'sb00000000000000000000;
      end
      else begin
        if (enb) begin
          if (internalReset == 1'b1) begin
            cBuff_im4 <= 20'sb00000000000000000000;
          end
          else begin
            cBuff_im4 <= cOut_im4;
          end
        end
      end
    end

  assign combOutreg_im = (cBuff_vout4 == 1'b0 ? invalidOut_im_1 :
              cBuff_im4);

  always @(posedge clk)
    begin : intdelay_21_process
      if (reset == 1'b0) begin
        combOut_im_1 <= 20'sb00000000000000000000;
      end
      else begin
        if (enb) begin
          if (internalReset == 1'b1) begin
            combOut_im_1 <= 20'sb00000000000000000000;
          end
          else begin
            combOut_im_1 <= combOutreg_im;
          end
        end
      end
    end

  always @(posedge clk)
    begin : intdelay_22_process
      if (reset == 1'b0) begin
        c_vout_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          if (internalReset == 1'b1) begin
            c_vout_1 <= 1'b0;
          end
          else begin
            c_vout_1 <= cBuff_vout4;
          end
        end
      end
    end

  assign combOut_re = combOut_re_1;

  assign combOut_im = combOut_im_1;

  assign c_vout = c_vout_1;

endmodule  // cSection

