// -------------------------------------------------------------
// 
// File Name: C:\Users\eslam\OneDrive\Desktop\Si clash\Fractional Sample Rate Conversion\Matlab files\codegen\finalCIC\hdlsrc\dsSection.v
// Created: 2025-11-21 17:16:16
// 
// Generated by MATLAB 25.2, MATLAB Coder 25.2 and HDL Coder 25.2
// 
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: dsSection
// Source Path: finalCIC/CICDecimation/dsSection
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module dsSection
          (clk,
           reset,
           enb,
           integOut_re,
           integOut_im,
           validInreg,
           downsampleVal,
           i_rstout,
           dsOut_re,
           dsOut_im,
           ds_vout);


  input   clk;
  input   reset;
  input   enb;
  input   signed [19:0] integOut_re;  // sfix20_En15
  input   signed [19:0] integOut_im;  // sfix20_En15
  input   validInreg;
  input   [11:0] downsampleVal;  // ufix12
  input   i_rstout;
  output  signed [19:0] dsOut_re;  // sfix20_En15
  output  signed [19:0] dsOut_im;  // sfix20_En15
  output  ds_vout;


  reg [5:0] downSampler_count;  // ufix6
  reg signed [19:0] downSampler_dataOutReg_re;  // sfix20
  reg signed [19:0] downSampler_dataOutReg_im;  // sfix20
  reg  downSampler_validOutReg;
  wire [5:0] downSampler_count_next;  // ufix6
  wire signed [19:0] downSampler_dataOutReg_re_next;  // sfix20_En15
  wire signed [19:0] downSampler_dataOutReg_im_next;  // sfix20_En15
  wire downSampler_validOutReg_next;
  wire [11:0] downSampler_sub_temp;  // ufix12
  wire [11:0] downSampler_1;  // ufix12


  always @(posedge clk)
    begin : downSampler_process
      if (reset == 1'b0) begin
        downSampler_count <= 6'b000000;
        downSampler_dataOutReg_re <= 20'sb00000000000000000000;
        downSampler_dataOutReg_im <= 20'sb00000000000000000000;
        downSampler_validOutReg <= 1'b0;
      end
      else begin
        if (enb) begin
          downSampler_count <= downSampler_count_next;
          downSampler_dataOutReg_re <= downSampler_dataOutReg_re_next;
          downSampler_dataOutReg_im <= downSampler_dataOutReg_im_next;
          downSampler_validOutReg <= downSampler_validOutReg_next;
        end
      end
    end

  assign downSampler_dataOutReg_re_next = (i_rstout != 1'b0 ? 20'sb00000000000000000000 :
              ((validInreg != 1'b0) && (downSampler_count == 6'b000000) ? integOut_re :
              downSampler_dataOutReg_re));
  assign downSampler_dataOutReg_im_next = (i_rstout != 1'b0 ? 20'sb00000000000000000000 :
              ((validInreg != 1'b0) && (downSampler_count == 6'b000000) ? integOut_im :
              downSampler_dataOutReg_im));
  assign downSampler_validOutReg_next = (i_rstout != 1'b0 ? 1'b0 :
              ((validInreg != 1'b0) && (downSampler_count == 6'b000000) ? 1'b1 :
              1'b0));
  assign downSampler_sub_temp = downsampleVal - 12'b000000000001;
  assign downSampler_1 = {6'b0, downSampler_count};
  assign downSampler_count_next = (i_rstout != 1'b0 ? 6'b000000 :
              (validInreg != 1'b0 ? (downSampler_1 < downSampler_sub_temp ? downSampler_count + 6'b000001 :
              6'b000000) :
              downSampler_count));
  assign dsOut_re = downSampler_dataOutReg_re;
  assign dsOut_im = downSampler_dataOutReg_im;
  assign ds_vout = downSampler_validOutReg;

endmodule  // dsSection

