// -------------------------------------------------------------
// 
// File Name: C:\Users\eslam\OneDrive\Desktop\Si clash\Fractional Sample Rate Conversion\Matlab files\codegen\finalCIC\hdlsrc\gcSection.v
// Created: 2025-11-21 17:16:16
// 
// Generated by MATLAB 25.2, MATLAB Coder 25.2 and HDL Coder 25.2
// 
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: gcSection
// Source Path: finalCIC/CICDecimation/gcSection
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module gcSection
          (combOut_re,
           combOut_im,
           downsampleValInd,
           internalReset,
           gcOut_re,
           gcOut_im);


  input   signed [19:0] combOut_re;  // sfix20_En15
  input   signed [19:0] combOut_im;  // sfix20_En15
  input   [11:0] downsampleValInd;  // ufix12
  input   internalReset;
  output  signed [19:0] gcOut_re;  // sfix20_En15
  output  signed [19:0] gcOut_im;  // sfix20_En15




  assign gcOut_re = combOut_re;

  assign gcOut_im = combOut_im;

endmodule  // gcSection

