// -------------------------------------------------------------
// 
// File Name: C:\Users\eslam\OneDrive\Desktop\Si clash\Fractional Sample Rate Conversion\Matlab files\codegen\finalCIC\hdlsrc\iSection.v
// Created: 2025-11-21 17:16:16
// 
// Generated by MATLAB 25.2, MATLAB Coder 25.2 and HDL Coder 25.2
// 
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: iSection
// Source Path: finalCIC/CICDecimation/iSection
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module iSection
          (clk,
           reset,
           enb,
           dataInreg,
           validInreg,
           internalReset,
           integOut_re,
           integOut_im);


  input   clk;
  input   reset;
  input   enb;
  input   signed [15:0] dataInreg;  // sfix16_En15
  input   validInreg;
  input   internalReset;
  output  signed [19:0] integOut_re;  // sfix20_En15
  output  signed [19:0] integOut_im;  // sfix20_En15


  wire signed [19:0] iIn_re1;  // sfix20_En15
  wire signed [19:0] iOut_re1;  // sfix20_En15
  wire signed [20:0] adder_add_cast;  // sfix21_En15
  wire signed [20:0] adder_add_cast_1;  // sfix21_En15
  wire signed [20:0] addOut_re1;  // sfix21_En15
  reg signed [20:0] iOutreg_re1;  // sfix21_En15
  wire signed [19:0] iOut_re2;  // sfix20_En15
  wire signed [20:0] adder_add_cast_2;  // sfix21_En15
  wire signed [20:0] adder_add_cast_3;  // sfix21_En15
  wire signed [20:0] addOut_re2;  // sfix21_En15
  reg signed [20:0] iOutreg_re2;  // sfix21_En15
  wire signed [19:0] iOut_re3;  // sfix20_En15
  wire signed [20:0] adder_add_cast_4;  // sfix21_En15
  wire signed [20:0] adder_add_cast_5;  // sfix21_En15
  wire signed [20:0] addOut_re3;  // sfix21_En15
  reg signed [20:0] iOutreg_re3;  // sfix21_En15
  wire signed [19:0] iOut_re4;  // sfix20_En15
  wire signed [20:0] adder_add_cast_6;  // sfix21_En15
  wire signed [20:0] adder_add_cast_7;  // sfix21_En15
  wire signed [20:0] addOut_re4;  // sfix21_En15
  reg signed [20:0] iOutreg_re4;  // sfix21_En15
  wire signed [15:0] dtc_im;  // sfix16_En15
  wire signed [19:0] iIn_im1;  // sfix20_En15
  wire signed [19:0] iOut_im1;  // sfix20_En15
  wire signed [20:0] adder_add_cast_8;  // sfix21_En15
  wire signed [20:0] adder_add_cast_9;  // sfix21_En15
  wire signed [20:0] addOut_im1;  // sfix21_En15
  reg signed [20:0] iOutreg_im1;  // sfix21_En15
  wire signed [19:0] iOut_im2;  // sfix20_En15
  wire signed [20:0] adder_add_cast_10;  // sfix21_En15
  wire signed [20:0] adder_add_cast_11;  // sfix21_En15
  wire signed [20:0] addOut_im2;  // sfix21_En15
  reg signed [20:0] iOutreg_im2;  // sfix21_En15
  wire signed [19:0] iOut_im3;  // sfix20_En15
  wire signed [20:0] adder_add_cast_12;  // sfix21_En15
  wire signed [20:0] adder_add_cast_13;  // sfix21_En15
  wire signed [20:0] addOut_im3;  // sfix21_En15
  reg signed [20:0] iOutreg_im3;  // sfix21_En15
  wire signed [19:0] iOut_im4;  // sfix20_En15
  wire signed [20:0] adder_add_cast_14;  // sfix21_En15
  wire signed [20:0] adder_add_cast_15;  // sfix21_En15
  wire signed [20:0] addOut_im4;  // sfix21_En15
  reg signed [20:0] iOutreg_im4;  // sfix21_En15


  assign iIn_re1 = {{4{dataInreg[15]}}, dataInreg};

  assign adder_add_cast = {iIn_re1[19], iIn_re1};
  assign adder_add_cast_1 = {iOut_re1[19], iOut_re1};
  assign addOut_re1 = adder_add_cast + adder_add_cast_1;

  always @(posedge clk)
    begin : intdelay_process
      if (reset == 1'b0) begin
        iOutreg_re1 <= 21'sb000000000000000000000;
      end
      else begin
        if (enb) begin
          if (internalReset == 1'b1) begin
            iOutreg_re1 <= 21'sb000000000000000000000;
          end
          else begin
            if (validInreg) begin
              iOutreg_re1 <= addOut_re1;
            end
          end
        end
      end
    end

  assign iOut_re1 = iOutreg_re1[19:0];

  assign adder_add_cast_2 = {iOut_re1[19], iOut_re1};
  assign adder_add_cast_3 = {iOut_re2[19], iOut_re2};
  assign addOut_re2 = adder_add_cast_2 + adder_add_cast_3;

  always @(posedge clk)
    begin : intdelay_1_process
      if (reset == 1'b0) begin
        iOutreg_re2 <= 21'sb000000000000000000000;
      end
      else begin
        if (enb) begin
          if (internalReset == 1'b1) begin
            iOutreg_re2 <= 21'sb000000000000000000000;
          end
          else begin
            if (validInreg) begin
              iOutreg_re2 <= addOut_re2;
            end
          end
        end
      end
    end

  assign iOut_re2 = iOutreg_re2[19:0];

  assign adder_add_cast_4 = {iOut_re2[19], iOut_re2};
  assign adder_add_cast_5 = {iOut_re3[19], iOut_re3};
  assign addOut_re3 = adder_add_cast_4 + adder_add_cast_5;

  always @(posedge clk)
    begin : intdelay_2_process
      if (reset == 1'b0) begin
        iOutreg_re3 <= 21'sb000000000000000000000;
      end
      else begin
        if (enb) begin
          if (internalReset == 1'b1) begin
            iOutreg_re3 <= 21'sb000000000000000000000;
          end
          else begin
            if (validInreg) begin
              iOutreg_re3 <= addOut_re3;
            end
          end
        end
      end
    end

  assign iOut_re3 = iOutreg_re3[19:0];

  assign adder_add_cast_6 = {iOut_re3[19], iOut_re3};
  assign adder_add_cast_7 = {iOut_re4[19], iOut_re4};
  assign addOut_re4 = adder_add_cast_6 + adder_add_cast_7;

  always @(posedge clk)
    begin : intdelay_3_process
      if (reset == 1'b0) begin
        iOutreg_re4 <= 21'sb000000000000000000000;
      end
      else begin
        if (enb) begin
          if (internalReset == 1'b1) begin
            iOutreg_re4 <= 21'sb000000000000000000000;
          end
          else begin
            if (validInreg) begin
              iOutreg_re4 <= addOut_re4;
            end
          end
        end
      end
    end

  assign iOut_re4 = iOutreg_re4[19:0];

  assign integOut_re = iOut_re4;

  assign dtc_im = 16'sb0000000000000000;

  assign iIn_im1 = {{4{dtc_im[15]}}, dtc_im};

  assign adder_add_cast_8 = {iIn_im1[19], iIn_im1};
  assign adder_add_cast_9 = {iOut_im1[19], iOut_im1};
  assign addOut_im1 = adder_add_cast_8 + adder_add_cast_9;

  always @(posedge clk)
    begin : intdelay_4_process
      if (reset == 1'b0) begin
        iOutreg_im1 <= 21'sb000000000000000000000;
      end
      else begin
        if (enb) begin
          if (internalReset == 1'b1) begin
            iOutreg_im1 <= 21'sb000000000000000000000;
          end
          else begin
            if (validInreg) begin
              iOutreg_im1 <= addOut_im1;
            end
          end
        end
      end
    end

  assign iOut_im1 = iOutreg_im1[19:0];

  assign adder_add_cast_10 = {iOut_im1[19], iOut_im1};
  assign adder_add_cast_11 = {iOut_im2[19], iOut_im2};
  assign addOut_im2 = adder_add_cast_10 + adder_add_cast_11;

  always @(posedge clk)
    begin : intdelay_5_process
      if (reset == 1'b0) begin
        iOutreg_im2 <= 21'sb000000000000000000000;
      end
      else begin
        if (enb) begin
          if (internalReset == 1'b1) begin
            iOutreg_im2 <= 21'sb000000000000000000000;
          end
          else begin
            if (validInreg) begin
              iOutreg_im2 <= addOut_im2;
            end
          end
        end
      end
    end

  assign iOut_im2 = iOutreg_im2[19:0];

  assign adder_add_cast_12 = {iOut_im2[19], iOut_im2};
  assign adder_add_cast_13 = {iOut_im3[19], iOut_im3};
  assign addOut_im3 = adder_add_cast_12 + adder_add_cast_13;

  always @(posedge clk)
    begin : intdelay_6_process
      if (reset == 1'b0) begin
        iOutreg_im3 <= 21'sb000000000000000000000;
      end
      else begin
        if (enb) begin
          if (internalReset == 1'b1) begin
            iOutreg_im3 <= 21'sb000000000000000000000;
          end
          else begin
            if (validInreg) begin
              iOutreg_im3 <= addOut_im3;
            end
          end
        end
      end
    end

  assign iOut_im3 = iOutreg_im3[19:0];

  assign adder_add_cast_14 = {iOut_im3[19], iOut_im3};
  assign adder_add_cast_15 = {iOut_im4[19], iOut_im4};
  assign addOut_im4 = adder_add_cast_14 + adder_add_cast_15;

  always @(posedge clk)
    begin : intdelay_7_process
      if (reset == 1'b0) begin
        iOutreg_im4 <= 21'sb000000000000000000000;
      end
      else begin
        if (enb) begin
          if (internalReset == 1'b1) begin
            iOutreg_im4 <= 21'sb000000000000000000000;
          end
          else begin
            if (validInreg) begin
              iOutreg_im4 <= addOut_im4;
            end
          end
        end
      end
    end

  assign iOut_im4 = iOutreg_im4[19:0];

  assign integOut_im = iOut_im4;

endmodule  // iSection

