// -------------------------------------------------------------
// 
// File Name: C:\Users\eslam\OneDrive\Desktop\Si clash\Fractional Sample Rate Conversion\Matlab files\codegen\FinalFirstNotch24\hdlsrc\dsphdl_BiquadFilter.v
// Created: 2025-11-21 22:55:38
// 
// Generated by MATLAB 25.2, MATLAB Coder 25.2 and HDL Coder 25.2
// 
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: dsphdl_BiquadFilter
// Source Path: FinalFirstNotch24/dsphdl.BiquadFilter
// Hierarchy Level: 1
// 
// Biquad Filter
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module dsphdl_BiquadFilter
          (clk,
           reset,
           enb,
           dataIn,
           validIn,
           dataOut,
           validOut);


  input   clk;
  input   reset;
  input   enb;
  input   signed [15:0] dataIn;  // sfix16_En15
  input   validIn;
  output  signed [15:0] dataOut;  // sfix16_En15
  output  validOut;


  reg signed [15:0] sec0reg;  // sfix16_En15
  wire signed [31:0] sec0mul;  // sfix32_En30
  reg signed [31:0] sec0mulreg;  // sfix32_En30
  wire signed [15:0] sec0dtc;  // sfix16_En15
  reg signed [15:0] sec0out;  // sfix16_En15
  reg  sec0validreg;
  reg  sec0mulvalidreg;
  reg  sec0validout;
  wire signed [15:0] sec1out;  // sfix16_En15
  wire sec1validout;
  reg  sec1mulvalidreg;
  reg  sec1validout_1;
  wire signed [15:0] zerooutconst;  // sfix16_En15
  wire signed [31:0] sec1mul;  // sfix32_En30
  reg signed [31:0] sec1mulreg;  // sfix32_En30
  wire signed [15:0] sec1dtc;  // sfix16_En15
  reg signed [15:0] sec1out_1;  // sfix16_En15
  wire signed [15:0] preout;  // sfix16_En15
  reg signed [15:0] dataOut_1;  // sfix16_En15
  reg  validOut_1;


  always @(posedge clk)
    begin : sec0dataregister_process
      if (reset == 1'b0) begin
        sec0reg <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          sec0reg <= dataIn;
        end
      end
    end

  assign sec0mul = 16'sb0111100110100000 * sec0reg;

  always @(posedge clk)
    begin : sec0muldataregister_process
      if (reset == 1'b0) begin
        sec0mulreg <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          sec0mulreg <= sec0mul;
        end
      end
    end

  assign sec0dtc = (((sec0mulreg[31] == 1'b0) && (sec0mulreg[30] != 1'b0)) || ((sec0mulreg[31] == 1'b0) && (sec0mulreg[30:15] == 16'sb0111111111111111)) ? 16'sb0111111111111111 :
              ((sec0mulreg[31] == 1'b1) && (sec0mulreg[30] != 1'b1) ? 16'sb1000000000000000 :
              sec0mulreg[30:15] + $signed({1'b0, sec0mulreg[14] & (( ~ sec0mulreg[31]) | (|sec0mulreg[13:0]))})));

  always @(posedge clk)
    begin : sec0OutRegister_process
      if (reset == 1'b0) begin
        sec0out <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          sec0out <= sec0dtc;
        end
      end
    end

  always @(posedge clk)
    begin : sec0validregister_process
      if (reset == 1'b0) begin
        sec0validreg <= 1'b0;
      end
      else begin
        if (enb) begin
          sec0validreg <= validIn;
        end
      end
    end

  always @(posedge clk)
    begin : sec0mulvalidregister_process
      if (reset == 1'b0) begin
        sec0mulvalidreg <= 1'b0;
      end
      else begin
        if (enb) begin
          sec0mulvalidreg <= sec0validreg;
        end
      end
    end

  always @(posedge clk)
    begin : sec0validoutregister_process
      if (reset == 1'b0) begin
        sec0validout <= 1'b0;
      end
      else begin
        if (enb) begin
          sec0validout <= sec0mulvalidreg;
        end
      end
    end

  BiquadDF2Section1 u_BiquadSection1_inst (.clk(clk),
                                           .reset(reset),
                                           .enb(enb),
                                           .dataIn(sec0out),  // sfix16_En15
                                           .validIn(sec0validout),
                                           .dataOut(sec1out),  // sfix16_En15
                                           .validOut(sec1validout)
                                           );

  always @(posedge clk)
    begin : sec1mulvalidregister_process
      if (reset == 1'b0) begin
        sec1mulvalidreg <= 1'b0;
      end
      else begin
        if (enb) begin
          sec1mulvalidreg <= sec1validout;
        end
      end
    end

  always @(posedge clk)
    begin : sec1validoutregister_process
      if (reset == 1'b0) begin
        sec1validout_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          sec1validout_1 <= sec1mulvalidreg;
        end
      end
    end

  assign zerooutconst = 16'sb0000000000000000;

  assign sec1mul = 16'sb0111111111111111 * sec1out;

  always @(posedge clk)
    begin : sec1muldataregister_process
      if (reset == 1'b0) begin
        sec1mulreg <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          sec1mulreg <= sec1mul;
        end
      end
    end

  assign sec1dtc = (((sec1mulreg[31] == 1'b0) && (sec1mulreg[30] != 1'b0)) || ((sec1mulreg[31] == 1'b0) && (sec1mulreg[30:15] == 16'sb0111111111111111)) ? 16'sb0111111111111111 :
              ((sec1mulreg[31] == 1'b1) && (sec1mulreg[30] != 1'b1) ? 16'sb1000000000000000 :
              sec1mulreg[30:15] + $signed({1'b0, sec1mulreg[14] & (( ~ sec1mulreg[31]) | (|sec1mulreg[13:0]))})));

  always @(posedge clk)
    begin : sec1OutRegister_process
      if (reset == 1'b0) begin
        sec1out_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          sec1out_1 <= sec1dtc;
        end
      end
    end

  assign preout = (sec1validout_1 == 1'b0 ? zerooutconst :
              sec1out_1);

  always @(posedge clk)
    begin : OutRegister_process
      if (reset == 1'b0) begin
        dataOut_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          dataOut_1 <= preout;
        end
      end
    end

  always @(posedge clk)
    begin : ValidOutRegister_process
      if (reset == 1'b0) begin
        validOut_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          validOut_1 <= sec1validout_1;
        end
      end
    end

  assign dataOut = dataOut_1;

  assign validOut = validOut_1;

endmodule  // dsphdl_BiquadFilter

